#!/usr/bin/env bash
set -euo pipefail

############################################################
# run_sedna.sh
#
# Canonical run pipeline for SEDNA.
#
# Can be called directly:
#   bash scripts/run_sedna.sh ...
#
# Or through the public CLI:
#   sedna run ...
#
# Pipeline:
#   FASTQ
#     -> bowtie2
#     -> name-sorted BAM
#     -> ngsLCA
#     -> no abundance outputs
############################################################

usage() {
    cat <<'USAGE'
Usage:
  sedna run \
    -i reads.fastq \
    -o output_dir \
    --ref-dir ncbi_reference_download \
    --taxdb-dir ncbi_tax_dmp \
    -t 16

Equivalent direct script usage:
  bash scripts/run_sedna.sh \
    -i reads.fastq \
    -o output_dir \
    --ref-dir ncbi_reference_download \
    --taxdb-dir ncbi_tax_dmp \
    -t 16

Required:
  -i, --input FILE          Input FASTQ/FASTQ.gz
  -o, --output DIR          Output directory
  --ref-dir DIR             Reference directory generated by sedna build-db
  --taxdb-dir DIR           Directory containing names.dmp, nodes.dmp, nucl_gb.accession2taxid

Optional:
  -t, --threads INT         Threads, default: 8
  --skip-bowtie2            Skip bowtie2 and use existing out.name_sorted.bam
  --skip-ngslca             Skip ngsLCA and use existing lca_results*
  --skip-abundance          Deprecated no-op; abundance outputs are disabled
  -h, --help                Show this help
USAGE
}

log() {
    echo "[$(date '+%F %T')] $*" >&2
}

die() {
    echo "[$(date '+%F %T')] ERROR: $*" >&2
    exit 1
}

need_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

find_lca_file() {
    local f

    for f in \
        lca_results \
        lca_results.gz \
        lca_results.lca \
        lca_results.lca.gz \
        lca_results.tsv \
        lca_results.tsv.gz \
        lca_results.txt \
        lca_results.txt.gz
    do
        if [[ -s "$f" ]]; then
            echo "$f"
            return 0
        fi
    done

    return 1
}

INPUT=""
OUTPUT_DIR=""
REF_DIR=""
TAXDB_DIR=""
THREADS=8

SKIP_BOWTIE2=0
SKIP_NGSLCA=0
SKIP_ABUNDANCE=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        -i|--input)
            INPUT="${2:-}"
            shift 2
            ;;
        -o|--output)
            OUTPUT_DIR="${2:-}"
            shift 2
            ;;
        --ref-dir)
            REF_DIR="${2:-}"
            shift 2
            ;;
        --taxdb-dir)
            TAXDB_DIR="${2:-}"
            shift 2
            ;;
        -t|--threads)
            THREADS="${2:-}"
            shift 2
            ;;
        --skip-bowtie2)
            SKIP_BOWTIE2=1
            shift
            ;;
        --skip-ngslca)
            SKIP_NGSLCA=1
            shift
            ;;
        --skip-abundance)
            SKIP_ABUNDANCE=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            die "Unknown argument: $1"
            ;;
    esac
done

[[ -n "$INPUT" ]] || die "Missing required argument: -i/--input"
[[ -n "$OUTPUT_DIR" ]] || die "Missing required argument: -o/--output"
[[ -n "$REF_DIR" ]] || die "Missing required argument: --ref-dir"
[[ -n "$TAXDB_DIR" ]] || die "Missing required argument: --taxdb-dir"
[[ "$THREADS" =~ ^[0-9]+$ ]] || die "--threads must be a positive integer"
[[ "$THREADS" -ge 1 ]] || die "--threads must be >= 1"

INPUT="$(readlink -f "$INPUT")"

mkdir -p "$OUTPUT_DIR"
OUTPUT_DIR="$(cd "$OUTPUT_DIR" && pwd)"

REF_DIR="$(readlink -f "$REF_DIR")"
TAXDB_DIR="$(readlink -f "$TAXDB_DIR")"

FASTA="${REF_DIR}/work_build_db/combined.dedup.fasta"
REF_PREFIX="${REF_DIR}/ncbi_reference"

NAMES_DMP="${TAXDB_DIR}/names.dmp"
NODES_DMP="${TAXDB_DIR}/nodes.dmp"
ACC2TAX="${TAXDB_DIR}/nucl_gb.accession2taxid"

cd "$OUTPUT_DIR"

log "INPUT: $INPUT"
log "OUTPUT_DIR: $OUTPUT_DIR"
log "REF_DIR: $REF_DIR"
log "REF_PREFIX: $REF_PREFIX"
log "FASTA: $FASTA"
log "TAXDB_DIR: $TAXDB_DIR"
log "THREADS: $THREADS"

need_cmd bowtie2
need_cmd samtools
need_cmd ngsLCA
need_cmd python3

[[ -s "$INPUT" ]] || die "Input FASTQ does not exist or is empty: $INPUT"
[[ -s "$FASTA" ]] || die "Reference FASTA does not exist or is empty: $FASTA"
[[ -s "$NAMES_DMP" ]] || die "names.dmp does not exist or is empty: $NAMES_DMP"
[[ -s "$NODES_DMP" ]] || die "nodes.dmp does not exist or is empty: $NODES_DMP"
[[ -s "$ACC2TAX" ]] || die "nucl_gb.accession2taxid does not exist or is empty: $ACC2TAX"

if compgen -G "${REF_PREFIX}.*.bt2" > /dev/null; then
    log "Detected bowtie2 small index: ${REF_PREFIX}.*.bt2"
elif compgen -G "${REF_PREFIX}.*.bt2l" > /dev/null; then
    log "Detected bowtie2 large index: ${REF_PREFIX}.*.bt2l"
else
    die "Could not find bowtie2 index: ${REF_PREFIX}.*.bt2 or ${REF_PREFIX}.*.bt2l"
fi

if [[ "$SKIP_BOWTIE2" -eq 0 ]]; then
    if [[ -s out.name_sorted.bam ]]; then
        log "out.name_sorted.bam already exists; skipping bowtie2"
    else
        log "Running bowtie2 and generating a name-sorted BAM"

        bowtie2 \
            -x "$REF_PREFIX" \
            -U "$INPUT" \
            -p "$THREADS" \
            --very-sensitive \
            2> bowtie2.log \
            | samtools sort \
                -n \
                -@ "$THREADS" \
                -m 2G \
                -o out.name_sorted.bam \
                -

        [[ -s out.name_sorted.bam ]] || die "out.name_sorted.bam was not created after bowtie2/samtools finished"

        log "BAM ready: $OUTPUT_DIR/out.name_sorted.bam"
    fi
else
    log "--skip-bowtie2 requested; skipping bowtie2"
    [[ -s out.name_sorted.bam ]] || die "--skip-bowtie2 was set but out.name_sorted.bam does not exist"
fi

if [[ "$SKIP_NGSLCA" -eq 0 ]]; then
    if LCA_EXISTING="$(find_lca_file 2>/dev/null)"; then
        log "Existing LCA file detected; skipping ngsLCA: $LCA_EXISTING"
    else
        log "Running ngsLCA"

        ngsLCA \
            -bam out.name_sorted.bam \
            -names "$NAMES_DMP" \
            -nodes "$NODES_DMP" \
            -acc2tax "$ACC2TAX" \
            -fix_ncbi 0 \
            -outnames lca_results \
            > ngsLCA.stdout.log \
            2> ngsLCA.stderr.log

        if LCA_AFTER="$(find_lca_file 2>/dev/null)"; then
            log "ngsLCA completed; LCA file: $LCA_AFTER"
        else
            log "Current output directory contents:"
            ls -lh >&2
            die "ngsLCA finished, but no lca_results* output file was found"
        fi
    fi
else
    log "--skip-ngslca requested; skipping ngsLCA"

    if LCA_SKIP="$(find_lca_file 2>/dev/null)"; then
        log "Using existing LCA file: $LCA_SKIP"
    else
        log "Current output directory contents:"
        ls -lh >&2
        die "--skip-ngslca was set but no usable LCA file was found, such as lca_results.lca"
    fi
fi

if [[ "$SKIP_ABUNDANCE" -eq 0 ]]; then
    log "Abundance tables and plots are disabled in this project; skipping this step"
else
    log "--skip-abundance requested; abundance outputs are already disabled"
fi

log "ALL DONE"
log "Output directory: $OUTPUT_DIR"

log "Main outputs:"
log "  BAM:"
log "    $OUTPUT_DIR/out.name_sorted.bam"

log "  LCA:"
log "    $OUTPUT_DIR/lca_results.lca or another lca_results* file"

log "  Logs:"
log "    $OUTPUT_DIR/bowtie2.log"
log "    $OUTPUT_DIR/ngsLCA.stderr.log"
